### ISSUE TITLE
global 设为 null 报错

### ISSUE THREAD

**Issue by Ttou** [longshihui/vue-cli-plugin-externals#1]
像一些库是没有导出的，如 `normalize.css`、`amfe-flexible`，该如何设置 `global`？

**Comment by longshihui** [comment]
刚刚试了下 确实有这个问题;
具体原因:  因为自动生成externals配置项没判断无导出模块。
我这边修复下，稍等~

**Comment by Ttou** [comment]
amfe-flexible 设为 null 后，编译出来的文件在访问时会报错
![20190319085615](https://user-images.githubusercontent.com/4298437/54572942-eef7b500-4a24-11e9-9b6c-581f16431e43.png)

**Comment by longshihui** [comment]
cdn方式的无导出模块不要在代码里显式写import语句
